package code

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"sega2asm/disasm/z80"
	"sega2asm/types"
)

func init() {
	types.Register("z80", processZ80)
}

func processZ80(ctx *types.Context) (*types.Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &types.Result{Includes: []types.Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}

	start := ctx.Start()
	data := ctx.ROMData()
	syms := ctx.Syms

	z80Org := uint32(ctx.Seg.Z80Org)
	results := z80.DisassembleBlock(data, 0, z80Org, uint32(len(data)), syms.ByAddr)

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Z80 Segment: %s  ROM:$%06X–$%06X\n\n", ctx.Seg.Name, start, ctx.End()))
	sb.WriteString(fmt.Sprintf("\torg\t$%04X\n\n", z80Org))

	labelHits := 0
	for _, res := range results {
		addr := res.Addr
		if syms.Has(addr) {
			labelHits++
			ctx.Logv("  [label] %s = $%04X", syms.Label(addr), addr)
			sb.WriteByte('\n')
			sb.WriteString(syms.Label(addr) + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else if addr == z80Org && ctx.Seg.Name != "" {
			sb.WriteByte('\n')
			sb.WriteString(ctx.Seg.Name + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else {
			sb.WriteString(fmt.Sprintf("; $%04X\n", addr))
		}
		sb.WriteString(res.Text)
		sb.WriteByte('\n')
	}

	// Append incbin directives for embedded data sections.
	if len(ctx.ExtraBins) > 0 {
		sb.WriteString("\n; Embedded data\n")
		for _, e := range ctx.ExtraBins {
			sb.WriteString(fmt.Sprintf("\tincbin\t'%s'\n", filepath.ToSlash(e.Path)))
		}
	}

	return &types.Result{
		Includes:  []types.Include{{Path: outPath}},
		LabelHits: labelHits,
	}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}
