package segments

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sega2asm/disasm/m68k"
	"sega2asm/disasm/z80"
	"sega2asm/types/code"
)

func init() {
	Register("m68k", processM68K)
	Register("z80", processZ80)
}

func processM68K(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	asmDir := filepath.Dir(outPath)
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}

	seg := ctx.Seg
	start := ctx.Start()
	end := ctx.End()
	data := ctx.ROMData()
	syms := ctx.Syms

	hints := code.BuildHintsMap(seg.Hints)
	results := m68k.DisassembleBlock(data, start, 0, uint32(len(data)), syms.ByAddr)

	// Resolve VDP ctrl symbol name.
	vdpCtrlSym := syms.Label(0xC00004)
	if !syms.Has(0xC00004) {
		if name := m68k.HWPortName(0xC00004); name != "" {
			vdpCtrlSym = name
		}
	}
	vdp := code.NewVDPAnnotator(vdpCtrlSym)

	// Collect branch targets within this segment.
	branchTargets := make(map[uint32]bool)
	for _, res := range results {
		if res.Target != 0 && res.Target >= start && res.Target < end {
			branchTargets[res.Target] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Segment: %s  $%06X–$%06X\n\n", seg.Name, start, end))
	sb.WriteString(fmt.Sprintf("\torg\t$%06X\n\n", start))

	sortedHintOffs := make([]uint32, 0, len(hints))
	for off := range hints {
		sortedHintOffs = append(sortedHintOffs, off)
	}
	sort.Slice(sortedHintOffs, func(i, j int) bool { return sortedHintOffs[i] < sortedHintOffs[j] })
	hintPtr := 0

	labelHits := 0
	lastHintEnd := uint32(0)

	flushHint := func(off uint32) {
		if off < lastHintEnd {
			return
		}
		hintAddr := start + off
		if syms.Has(hintAddr) {
			labelHits++
			sb.WriteByte('\n')
			sb.WriteString(syms.Label(hintAddr) + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%06X\n", hintAddr))
		}
		code.EmitHint(&sb, hints[off], data, off, ctx.Charmap, syms, asmDir)
		lastHintEnd = off + uint32(hints[off].Length)
	}

	for _, res := range results {
		addr := res.Addr
		curOff := addr - start

		for hintPtr < len(sortedHintOffs) && sortedHintOffs[hintPtr] < curOff {
			flushHint(sortedHintOffs[hintPtr])
			hintPtr++
		}

		labelEmitted := false
		if syms.Has(addr) {
			labelHits++
			ctx.Logv("  [label] %s = $%06X", syms.Label(addr), addr)
			sb.WriteByte('\n')
			sb.WriteString(syms.Label(addr) + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%06X\n", addr))
			labelEmitted = true
		} else if addr == ctx.ROM.InitialPC {
			sb.WriteByte('\n')
			sb.WriteString("EntryPoint:")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%06X\n", addr))
			labelEmitted = true
		} else if addr == start && seg.Name != "" {
			sb.WriteByte('\n')
			sb.WriteString(seg.Name + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%06X\n", addr))
			labelEmitted = true
		} else if branchTargets[addr] {
			sb.WriteByte('\n')
			sb.WriteString(fmt.Sprintf("loc_%06X:", addr))
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%06X\n", addr))
			labelEmitted = true
		}

		if hint, ok := hints[curOff]; ok {
			for hintPtr < len(sortedHintOffs) && sortedHintOffs[hintPtr] <= curOff {
				hintPtr++
			}
			code.EmitHint(&sb, hint, data, curOff, ctx.Charmap, syms, asmDir)
			lastHintEnd = curOff + uint32(hint.Length)
			continue
		}

		if curOff < lastHintEnd {
			continue
		}

		if !labelEmitted {
			sb.WriteString(fmt.Sprintf("; $%06X\n", addr))
		}
		sb.WriteString(vdp.Annotate(res.Text))
		sb.WriteByte('\n')
	}

	for hintPtr < len(sortedHintOffs) {
		flushHint(sortedHintOffs[hintPtr])
		hintPtr++
	}

	splitHints := code.SuggestM68KSplits(results, seg, syms, ctx.ROM.Data)

	return &Result{
		Includes:  []Include{{Path: outPath}},
		Hints:     splitHints,
		LabelHits: labelHits,
	}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}

func processZ80(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}

	start := ctx.Start()
	data := ctx.ROMData()
	syms := ctx.Syms

	z80Org := uint32(ctx.Seg.Z80Org)
	results := z80.DisassembleBlock(data, 0, z80Org, uint32(len(data)), syms.ByAddr)

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Z80 Segment: %s  ROM:$%06X–$%06X\n\n", ctx.Seg.Name, start, ctx.End()))
	sb.WriteString(fmt.Sprintf("\torg\t$%04X\n\n", z80Org))

	labelHits := 0
	for _, res := range results {
		addr := res.Addr
		if syms.Has(addr) {
			labelHits++
			ctx.Logv("  [label] %s = $%04X", syms.Label(addr), addr)
			sb.WriteByte('\n')
			sb.WriteString(syms.Label(addr) + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else if addr == z80Org && ctx.Seg.Name != "" {
			sb.WriteByte('\n')
			sb.WriteString(ctx.Seg.Name + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else {
			sb.WriteString(fmt.Sprintf("; $%04X\n", addr))
		}
		sb.WriteString(res.Text)
		sb.WriteByte('\n')
	}

	if len(ctx.ExtraBins) > 0 {
		sb.WriteString("\n; Embedded data\n")
		for _, e := range ctx.ExtraBins {
			sb.WriteString(fmt.Sprintf("\tincbin\t'%s'\n", filepath.ToSlash(e.Path)))
		}
	}

	return &Result{
		Includes:  []Include{{Path: outPath}},
		LabelHits: labelHits,
	}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}
