package segments

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func init() {
	Register("header", processHeader)
}

func processHeader(ctx *Context) (*Result, error) {
	seg := ctx.Seg
	segDir := filepath.Join(ctx.AsmDir, func() string {
		if seg.SubDir != "" {
			return seg.SubDir
		}
		return strings.ToLower(seg.Type)
	}())
	interruptsPath := filepath.Join(segDir, "interrupts.asm")
	headerPath := ctx.SegPath(ctx.AsmDir, ".asm")

	if ctx.DryRun {
		return &Result{Includes: []Include{
			{Path: interruptsPath},
			{Path: headerPath},
		}}, nil
	}
	if err := os.MkdirAll(segDir, 0755); err != nil {
		return nil, err
	}

	r := ctx.ROM
	syms := ctx.Syms

	// ── interrupts.asm ($000000–$0000FF) ──────────────────────────────────
	var iv strings.Builder
	iv.WriteString("; Auto-generated by sega2asm\n")
	iv.WriteString("; Interrupt Vector Table\n\n")
	iv.WriteString("\torg\t$000000\n\n")

	vectorLabels := []string{
		"InitialSSP", "InitialPC", "BusError", "AddressError",
		"IllegalInstr", "ZeroDivide", "CHKExcept", "TRAPVExcept",
		"PrivilegeViol", "TraceExcept", "Line1010Emul", "Line1111Emul",
		"Reserved0C", "Reserved0D", "Reserved0E", "UninitialisedISR",
		"Reserved10", "Reserved11", "Reserved12", "Reserved13",
		"Reserved14", "Reserved15", "Reserved16", "Reserved17",
		"SpuriousIRQ", "IRQ1", "EXT_IRQ", "IRQ3",
		"HBLANK_IRQ", "IRQ5", "VBLANK_IRQ", "IRQ7",
	}
	resolveVec := func(addr uint32) string {
		if name := syms.Label(addr); name != "" {
			return name
		}
		return fmt.Sprintf("$%08X", addr)
	}
	for i, label := range vectorLabels {
		v := r.Read32(uint32(i * 4))
		iv.WriteString(fmt.Sprintf("%-24s\tdc.l\t%s\n", label+":", resolveVec(v)))
	}
	for i := 32; i < 64; i++ {
		v := r.Read32(uint32(i * 4))
		iv.WriteString(fmt.Sprintf("TRAP_%02d:\t\t\tdc.l\t%s\n", i-32, resolveVec(v)))
	}
	if err := os.WriteFile(interruptsPath, []byte(iv.String()), 0644); err != nil {
		return nil, err
	}

	// ── header.asm ($000100–$0001FF) ──────────────────────────────────────
	var hb strings.Builder
	hb.WriteString("; Auto-generated by sega2asm\n")
	hb.WriteString("; Mega Drive ROM Header\n\n")
	hb.WriteString("\torg\t$000100\n\n")

	h := r.Header
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-16s'\n", h.SystemName))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-16s'\n", h.Copyright))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-48s'\n", h.DomesticName))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-48s'\n", h.OverseasName))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%s'\n", h.SerialType))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-12s'\n", h.Serial))
	hb.WriteString(fmt.Sprintf("\tdc.w\t$%04X\t; Checksum\n", h.Checksum))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-16s'\n", h.DeviceSupport))
	hb.WriteString("\tdc.l\tRomStart\n")
	hb.WriteString("\tdc.l\tRomEnd\n")
	hb.WriteString("\tdc.l\tRAM_START\n")
	hb.WriteString("\tdc.l\tRAM_END\n")
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-12s'\n", h.SRAMInfo))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-52s'\n", h.Notes))
	hb.WriteString(fmt.Sprintf("\tdc.b\t'%-16s'\t; Region\n", h.RegionCodes))

	if err := os.WriteFile(headerPath, []byte(hb.String()), 0644); err != nil {
		return nil, err
	}

	return &Result{Includes: []Include{
		{Path: interruptsPath},
		{Path: headerPath},
	}}, nil
}
